# Generated by Django 4.1.4 on 2022-12-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('abbreviation', models.CharField(max_length=8, verbose_name='Аббревиатура')),
                ('code', models.CharField(max_length=15, unique=True, verbose_name='Код специальности')),
            ],
        ),
    ]
