# Generated by Django 4.1.4 on 2022-12-06 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_speciality'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('number', models.CharField(max_length=10, verbose_name='Номер группы')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.speciality')),
                ('subjects', models.ManyToManyField(blank=True, to='app.subject')),
            ],
        ),
    ]
